### ISSUE TITLE
Log authentications

### ISSUE THREAD

**Issue by j2jensen** [HealthCatalyst/Fabric.Identity#192]
Sometimes a client's security department will want to know who's logged in to a given tool, and when. (This can be useful in a HIPAA audit, for example.)

I've heard through the grapevine that Fabric.Identity is currently only tracking the most recent login for a given user, overwriting their last timestamp with each new visit. We need information about who is logging in to be kept in logs for years.

**Comment by michaelvidal24** [comment]
Sounds like there might be some confusion as to what we currently do, so let me help to clarify. We have two separate mechanism that track user login information:

1) We track the last login time per user per application that is tied to a user. This is the functionality I believe you are referring to, and it really exists to allow a UI to show a user's last login time easily.

This is separate from our:

2) Event logging that tracks and records every authentication event. These events are currently persisted to application insights, but in the current release we are working on these events will be persisted in the Identity database instead of application insights. We leverage IdentityServer4's built in event system for this: https://identityserver4.readthedocs.io/en/release/topics/events.html, and log the events through serilog to AI.

The first case is really for an access control UI to show the last login time for a user for a particular app easily. The second is for satisfying audits and in the future for automatically detecting anomalies in authentication events that could signify malicious behavior. Eventually we will build a UI on top of the audit data as well.

**Comment by j2jensen** [comment]
Thanks, Michael. That's really great information.
